### PR TITLE
fix(go): override default HTTP client timeout

### LINKED ISSUE #39: Long-running queries fail at ~60s due to HTTP client timeout, ignoring Go context
When executing a Trino query that takes longer than approximately 60 seconds to return results, the ADBC driver fails with a `[Trino] context deadline exceeded` error. This happens even when a much longer timeout (e.g. 10 minutes) has been set on the context.

Image

Also, from the Trino server logs, it confirms the query was `USER_CANCELED` at about 60 seconds which indicates the client (the ADBC driver) terminated the HTTP long-poll request:

Image

**Steps to Reproduce**
Following the [go example](https://github.com/columnar-tech/adbc-quickstarts/tree/main/go/trino) to setup my local environment and change the SQL to a long running query e.g. `SELECT * from tpcds.sf10.inventory`

**Question**
Is there a specific database option or environment variable has been exposed to configure the driver's internal HTTP request timeout?

### PR DESCRIPTION
**Pull request by Mandukhai-Alimaa**
## What's Changed

When query_timeout is set in DSN, automatically create and register a custom HTTP client with matching timeout. This prevents HTTP-level timeouts during long-running queries.

Closes #39 .

### CODE REVIEW

**Comment by lidavidm** [comment]
The docs claim there is no timeout by default, though, and that the context timeout is used instead. Maybe instead of matching the parameter, we should set the HTTP timeout to (effectively) unlimited? (We should also verify that the context timeout actually still takes effect in this case.)

https://github.com/trinodb/trino-go-client?tab=readme-ov-file#querytimeout

File: go/db_factory.go [hunk 1]
```diff
@@ -42,9 +46,53 @@ func (f *TrinoDBFactory) CreateDB(ctx context.Context, driverName string, opts m
...
 
+// registerCustomClientForTimeout creates and registers a custom HTTP client with a 10-hour timeout.
+// This prevents infrastructure/network timeouts during long-running queries
+func (f *TrinoDBFactory) registerCustomClientForTimeout(dsn string) (string, error) {
+	cfg, err := trino.ParseDSN(dsn)
+	if err != nil {
+		return "", fmt.Errorf("failed to parse DSN: %v", err)
+	}
+
+	const httpClientTimeout = 10 * time.Hour
```
Comment (lidavidm) [inline go/db_factory.go]: I think we can use QueryTimeout from the DSN if set, and only use 10 hours if it's not set? (Also, trino appears to expose the timeout as a duration from its package, so can we just reference that and not hardcode it here?)

File: go/db_factory.go [hunk 2]
```diff
@@ -42,9 +46,53 @@ func (f *TrinoDBFactory) CreateDB(ctx context.Context, driverName string, opts m
...
+				Timeout:   30 * time.Second,
+				KeepAlive: 30 * time.Second,
+				DualStack: true,
+			}).DialContext,
+			MaxIdleConns:          100,
+			IdleConnTimeout:       90 * time.Second,
+			TLSHandshakeTimeout:   10 * time.Second,
+			ResponseHeaderTimeout: httpClientTimeout, // Timeout for response headers
+			ExpectContinueTimeout: 1 * time.Second,
+		},
```
Comment (lidavidm) [inline go/db_factory.go]: Is it possible to avoid hardcoding the rest of these constants and let them take whatever the default value is?

File: go/db_factory.go [hunk 3]
```diff
@@ -42,9 +47,51 @@ func (f *TrinoDBFactory) CreateDB(ctx context.Context, driverName string, opts m
...
 
+// registerCustomClientForTimeout creates and registers a custom HTTP client
+// This prevents infrastructure/network timeouts during long-running queries
+func (f *TrinoDBFactory) registerCustomClientForTimeout(dsn string) (string, error) {
+	cfg, err := trino.ParseDSN(dsn)
+	if err != nil {
+		return "", fmt.Errorf("failed to parse DSN: %v", err)
+	}
+
+	const httpClientName = "abdc_trino_timeout"
```
[the remark this answers is not in the document]
Comment (Mandukhai-Alimaa) [reply go/db_factory.go]: XD
